apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
        - name: example-app
          image: enegu/otus-nginx:1.3
          ports:
          - name: web
            containerPort: 8080
        - name: nginx-prometheus-exporter
          image: "nginx/nginx-prometheus-exporter:0.8.0"
          imagePullPolicy: Always
          args: ["-nginx.scrape-uri", "http://localhost:8080/basic_status"]
          ports:
            - containerPort: 9113
              name: http
