kind: Service
apiVersion: v1
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  selector:
    app: nginx-prometheus-exporter
  ports:
  - name: webqq
    port: 9113

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-prometheus-exporter
#   annotations:
#     prometheus.io/scrape: 'true'
#     prometheus.io/port:   '9113'
# spec:
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: 9113
#   selector:
#     app: nginx-prometheus-exporter