apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-prometheus-exporter
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  endpoints:
  - port: webqq
